const fs = require('node:fs');
const path = require('node:path');

const rootDir = process.cwd();
const packagesDir = path.join(rootDir, 'packages');
const srcDir = path.join(rootDir, 'src');
const outputFile = path.join(srcDir, 'auto-modules.js');

const packageNames = fs
  .readdirSync(packagesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .filter((name) => fs.existsSync(path.join(packagesDir, name, 'src', 'index.js')))
  .sort();

const importLines = packageNames.map(
  (name) => `import * as ${name}Module from '../packages/${name}/src/index.js';`,
);
const exportLines = packageNames.map((name) => `export * from '../packages/${name}/src/index.js';`);
const mapLines = packageNames.map((name) => `  ${name}: ${name}Module,`);

const content = `// Auto-generated by scripts/generate-modules.js. Do not edit manually.\n\n${importLines.join('\n')}\n\n${exportLines.join('\n')}\n\nexport const modules = {\n${mapLines.join('\n')}\n};\n`;

fs.mkdirSync(srcDir, { recursive: true });
fs.writeFileSync(outputFile, content);
console.log(`Generated ${path.relative(rootDir, outputFile)} with ${packageNames.length} modules.`);
