// Auto-generated by scripts/generate-modules.js. Do not edit manually.

import * as adminPlugin from '../packages/admin/src/index.js';
import * as aoilayerPlugin from '../packages/aoilayer/src/index.js';
import * as heatmapPlugin from '../packages/heatmap/src/index.js';
import * as servicePlugin from '../packages/service/src/index.js';

export * from '../packages/admin/src/index.js';
export * from '../packages/aoilayer/src/index.js';
export * from '../packages/heatmap/src/index.js';
export * from '../packages/service/src/index.js';

export const plugins = {
  admin: adminPlugin,
  aoilayer: aoilayerPlugin,
  heatmap: heatmapPlugin,
  service: servicePlugin,
};
