// Auto-generated by scripts/generate-modules.js. Do not edit manually.

import * as adminModule from '../packages/admin/src/index.js';
import * as aoilayerModule from '../packages/aoilayer/src/index.js';
import * as heatmapModule from '../packages/heatmap/src/index.js';
import * as serviceModule from '../packages/service/src/index.js';
import * as sharedModule from '../packages/shared/src/index.js';

export * from '../packages/admin/src/index.js';
export * from '../packages/aoilayer/src/index.js';
export * from '../packages/heatmap/src/index.js';
export * from '../packages/service/src/index.js';
export * from '../packages/shared/src/index.js';

export const modules = {
  admin: adminModule,
  aoilayer: aoilayerModule,
  heatmap: heatmapModule,
  service: serviceModule,
  shared: sharedModule,
};
